### ISSUE TITLE
Port 443 (HTTPS) wird nicht übergeben

### ISSUE THREAD

**Issue by Flol0** [elabit/checkmk_gematik_tikonn#1]
Hallo Simon,

ich habe den Agenten soeben installiert und auch einen Konnektor einer Zahnarztpraxis erfolgreich anbinden können. 
In unseren Kliniken ist allerdings kein Zugriff über Port 80 auf den Konnektor erlaubt. Daher funktioniert hier der Check leider nicht.

Ändere ich manuell auf Port 443 wird dieser scheinbar nichtmal übergeben wenn ich die Ausgabe von cmk --check-discovery Konnektor -vv ansehe.

**Comment by simonmeggle** [comment]
Juhu, der erste Bug 🥳 
Ich sehe mir das an!
VG Simon

**Comment by simonmeggle** [comment]
Könntest Du bitte versuchshalber in `checks/agent_gematik_tikonn` folgende Ergänzung (schnipp-schnapp) machen und mir Bescheid geben, ob es damit funktioniert? 

```PYTHON
    args = [
        "--hostname",
        ipaddress,
#---- 8< ----
        "--port",
        params["port"],
#---- >8 ----
        "--mandant",
        params["mandant_id"],
        "--client",
        params["client_id"],
        "--workplaces",
        workplace_ids,
        "--wsdlversion",
        "EventService:{}".format(wsdl_v_eventservice),
        "--wsdlversion",
        "SignatureService:{}".format(wsdl_v_signatureservice),
    ]
```

**Comment by Flol0** [comment]
Hallo Simon,

Übernommen wird der Port jetzt. Funktionieren tut es leider noch nicht.

`+ PARSE FETCHER RESULTS
  Source: SourceType.HOST/FetcherType.PROGRAM
  -> Not adding sections: Agent exited with code 1: Caught unhandled ConnectionError(('Connection aborted.', BadStatusLine('\x15\x03\x03\x00\x02\x02P'))) in /omd/sites/testkonnektor/lib/python3/cmk/special_agents/utils/agent_common.py:135`



Ich habe so auch einen Unterschied in der Übergabe der Parameter festgestellt, falls das was ausmachen könnte.
`'--port' 443 '--mandant' '01'`

**Comment by simonmeggle** [comment]
Ok, war ein Schnellschuss. Ich debugge das mal.
