### ISSUE TITLE
Parsing of section gematik_tikonn failed

### ISSUE THREAD

**Issue by djalexz** [elabit/checkmk_gematik_tikonn#5]
Hallo, ich bekomme beim Versuch eine Verbindung aufzubauen folgende Meldung:

![image](https://user-images.githubusercontent.com/11389551/198396179-67329eee-534b-4fa5-a160-81cd4ab5aa1b.png)

Daten zum Konnektor habe ich per Google Formular gesendet.

Hier noch die Settings:
![image](https://user-images.githubusercontent.com/11389551/198397255-59cb06c0-81eb-43cb-8104-5371443ac9a7.png)

Mit Port 80 bekomme ich:

`[special_gematik_tikonn] Agent exited with code 1: Caught unhandled TransportError(Server returned HTTP status 403 (no content available)) in /omd/sites/monitoring/lib/python3/cmk/special_agents/utils/agent_common.py:135CRIT, execution time 0.6 sec`

Vielen Dank für das tolle Projekt.
Endlich nimmt sich mal jemand dem Thema an :-)

LG Alex

**Comment by simonmeggle** [comment]
follow up in #8
